- 套接字有许多可以配置的选项
- 这些选项时根据协议来划分的, 比如scoket的配置，IP协议的配置，TCP协议的配置等

接下来会介绍一些比较重要的配置

=== SO_SNDBF & SO_RCVBUF

- socket 的输入，输出缓冲区大小

- 缓冲区的大小的设置需要谨慎处理，因此系统不会完全按照传递的参数进行设置

=== SO_REUSEADDR

==== Time-wait 状态

- 当某台主机想要终止连接时，会向另一台主机发送 FIN消息

- 但是套接字不是在经过四次握手过程后立即消除，而是要经过一段时间的Time-wait 状态

- 先断开连接(先发送 FIN 消息)的主机才会有 Time-wait 状态

- 所以假如服务器端先断开连接，那么就会无法立即运行。套接字处在 Time-wait 过程时，相应端口是正在使用的状态

==== Time-wait 的作用

假设主机A向主机B传输ACK消息 (SEQ 5001, ACK 7502)后立即消除套接字，但是最后这条ACK消息在传输途中丢失，未能传给主机B。此时，主机B会认为之前自己发送的FIN消息未能抵达主机A，继而视图重传，但是主机A已经是完全终止的状态，因此主机B永远无法收到主机A最后传来的ACK消息。

Time-wait 就是为了防止这种情况

==== 解决办法
可以通过更改 `SO_REUSEADDR` 的状态。假如该值为 true, 那么可以在 `Time-wait` 状态下的套接字端口号重新分配给新的套接字

该值默认为false


=== TCP_NODELAY 

- 控制是否要开启 `nagle` 算法

- nagle 算法的核心在于 只有收到前一数据的ACK消息时，Nagle算法才发送下一数据

比如为了发送字符串 Nagle, 先发送 "N" 字符，因为"N"字符之前没有其它数据（无需等待ACK），因此立即传输

之后开始等待 "N" 字符的ack消息，等待的时候，剩下 "agle" 都会填入输出缓冲

收到字符"N"的ACK消息后，将输出缓冲的"agle"装入一个数据包发送

假如不开启 `nagle` 算法，那么数据到达输出缓冲后将立即被发送出去,那么此时有可能会多发很多数据包出去

- nagle 算法并不是什么时候都适用，根据传输数据的特性。网络流量未受太大影响时，不使用 nagle 算法要比使用它时传输数据快，比较典型的情况就是 传输大文件数据








